#!/bin/sh
# update.sh — single entry point for deploying and running code on home devices.
# POSIX sh; works under both `./update.sh` and `sh update.sh`.
#
# Future work:
#   - manage cron entries
#   - run pre-deploy lint
#   - support per-device pre_update.sh and post_update.sh hooks

set -eu
ROOT_DIR="$(cd "$(dirname "$0")" && pwd)"
DEVICES_DIR="$ROOT_DIR/devices"

# Centralized, git-ignored secrets. Sourced here so every device (Arduino
# compile-time #defines, the Pi EnvironmentFile) draws from one file.
ENV_FILE="$ROOT_DIR/.env"

# shellcheck disable=SC1090
[ -f "$ENV_FILE" ] && . "$ENV_FILE"

# Any arduino_secrets.h is generated for a single compile and must never
# persist. This net catches the normal path, early returns, and Ctrl-C.
cleanup_secrets() {
    find "$DEVICES_DIR" -name arduino_secrets.h -type f -delete 2>/dev/null || true
}
trap cleanup_secrets EXIT INT TERM

list_all_devices() {
    for d in "$DEVICES_DIR"/*/; do
        [ -d "$d" ] || continue
        [ -f "$d/device.conf" ] || continue
        basename "$d"
    done
}

update_device() {
    name="$1"
    dir="$DEVICES_DIR/$name"
    conf="$dir/device.conf"

    echo
    echo "================================================================"
    echo "  Device: $name"
    echo "================================================================"

    if [ ! -f "$conf" ]; then
        echo "  ERROR: $conf not found" >&2
        return 1
    fi
    if [ ! -d "$dir/files" ]; then
        echo "  ERROR: $dir/files/ not found" >&2
        return 1
    fi

    SSH_TARGET=""; REMOTE_DIR=""; VENV_PYTHON=""; ENTRYPOINT=""; RUN_AS_ROOT="false"; SCREEN_NAME=""; SYSTEMD_UNIT=""
    ARDUINO_FQBN=""; ARDUINO_OTA_ADDRESS=""; ARDUINO_SKETCH=""
    # shellcheck disable=SC1090
    . "$conf"

    if [ -n "$SCREEN_NAME" ] && [ -n "$SYSTEMD_UNIT" ]; then
        echo "  ERROR: SCREEN_NAME and SYSTEMD_UNIT are mutually exclusive" >&2
        return 1
    fi
    if [ -n "$ARDUINO_FQBN" ] && { [ -n "$SCREEN_NAME" ] || [ -n "$SYSTEMD_UNIT" ]; }; then
        echo "  ERROR: ARDUINO_FQBN is exclusive with SCREEN_NAME/SYSTEMD_UNIT" >&2
        return 1
    fi

    # Arduino-OTA mode: no SSH/rsync/systemd. Compile with the generated
    # secrets header, upload over Wi-Fi, then wipe the header. This is the
    # Arduino analog of the rsync deploy path below.
    if [ -n "$ARDUINO_FQBN" ]; then
        if ! command -v arduino-cli >/dev/null 2>&1; then
            echo "  ERROR: arduino-cli not on PATH (required for Arduino-OTA devices)" >&2
            return 1
        fi
        missing=""
        for v in SECRET_SSID SECRET_PASS SECRET_OTA_PASS MQTT_HOST MQTT_PORT; do
            eval "val=\${$v:-}"
            [ -n "$val" ] || missing="$missing $v"
        done
        if [ -n "$missing" ]; then
            echo "  ERROR: missing keys in $ENV_FILE:$missing" >&2
            return 1
        fi

        sketch_dir="$dir/files/$ARDUINO_SKETCH"
        secrets_h="$sketch_dir/arduino_secrets.h"

        # Prefer a wired board if one is plugged in — no manual first flash.
        # Match the FQBN on a serial line of `board list`; the same board on
        # Wi-Fi shows up with protocol "network", so USB always wins when both
        # are present. $1=Port, $2=Protocol (Port never contains spaces).
        usb_port="$(arduino-cli board list 2>/dev/null | awk -v fqbn="$ARDUINO_FQBN" '$0 ~ fqbn && $2 == "serial" { print $1; exit }')"
        if [ -n "$usb_port" ]; then
            echo "  Mode:      arduino-usb ($ARDUINO_FQBN @ $usb_port)"
        else
            echo "  Mode:      arduino-ota ($ARDUINO_FQBN -> $ARDUINO_OTA_ADDRESS)"
        fi

        cat > "$secrets_h" <<EOF
// AUTO-GENERATED by update.sh from $ENV_FILE — do not commit, do not edit.
#pragma once
#define SECRET_SSID "$SECRET_SSID"
#define SECRET_PASS "$SECRET_PASS"
#define SECRET_OTA_PASS "$SECRET_OTA_PASS"
#define MQTT_HOST "$MQTT_HOST"
#define MQTT_PORT $MQTT_PORT
EOF

        # Explicit rc handling: set -e is disabled inside a function called
        # from `if`, so guard each step and always remove the header.
        rc=0
        echo "  -> arduino-cli compile"
        arduino-cli compile --fqbn "$ARDUINO_FQBN" "$sketch_dir" || rc=$?
        if [ "$rc" -eq 0 ] && [ -n "$usb_port" ]; then
            echo "  -> arduino-cli upload (USB) to $usb_port"
            # No --upload-field: the serial protocol has no password field.
            arduino-cli upload -p "$usb_port" --fqbn "$ARDUINO_FQBN" "$sketch_dir" || rc=$?
        elif [ "$rc" -eq 0 ]; then
            echo "  -> arduino-cli upload (network/OTA) to $ARDUINO_OTA_ADDRESS"
            arduino-cli upload -p "$ARDUINO_OTA_ADDRESS" --fqbn "$ARDUINO_FQBN" \
                --upload-field password="$SECRET_OTA_PASS" "$sketch_dir" || rc=$?
        fi
        rm -f "$secrets_h"
        [ "$rc" -eq 0 ] && return 0
        echo "  ERROR: arduino-cli failed (rc=$rc)" >&2
        return 1
    fi

    echo "  Target:    $SSH_TARGET"
    echo "  RemoteDir: $REMOTE_DIR"
    echo "  Entry:     $ENTRYPOINT (root=$RUN_AS_ROOT, screen=${SCREEN_NAME:-no}, systemd=${SYSTEMD_UNIT:-no})"

    sudo_prefix=""
    [ "$RUN_AS_ROOT" = "true" ] && sudo_prefix="sudo "

    # Pre-stop the running process BEFORE rsyncing, so we don't replace files
    # under a live interpreter. Both stop paths swallow the "not running" case.
    if [ -n "$SCREEN_NAME" ]; then
        echo "  -> kill screen '$SCREEN_NAME' on remote"
        ssh -t "$SSH_TARGET" "${sudo_prefix}screen -S $SCREEN_NAME -X quit 2>/dev/null || true"
    elif [ -n "$SYSTEMD_UNIT" ]; then
        echo "  -> systemctl stop $SYSTEMD_UNIT"
        ssh -t "$SSH_TARGET" "sudo systemctl stop $SYSTEMD_UNIT 2>/dev/null || true"
    fi

    echo "  -> rsync $dir/files/ -> $SSH_TARGET:$REMOTE_DIR/"
    # Excludes protect remote-only state from --delete. venv/.venv hold the
    # Python virtualenv, bootstrapped once per device (see device README);
    # without these excludes, --delete wipes the venv on every deploy.
    # hex_state.json holds the HomeKit pairing keys for raspberry-hex; wiping
    # it forces re-pairing from the iPhone on every deploy. home.db is the
    # single SQLite store for sensor history/state; wiping it loses all
    # recorded readings (-wal/-shm are its WAL sidecar files).
    rsync -az --delete \
        --exclude='venv/' --exclude='.venv/' \
        --exclude='hex_state.json' \
        --exclude='home.db' --exclude='home.db-wal' --exclude='home.db-shm' \
        -e ssh "$dir/files/" "$SSH_TARGET:$REMOTE_DIR/"

    if [ -n "$SYSTEMD_UNIT" ]; then
        # Ship Pi-side secrets as a root-only EnvironmentFile, referenced by
        # the unit as `EnvironmentFile=-/etc/home-server.env`. Pushed over ssh
        # (not rsync) so it never lands in REMOTE_DIR or git. Plain ssh (no
        # -t) so the heredoc reaches install's stdin; relies on NOPASSWD sudo.
        if [ -n "${MQTT_HOST:-}" ]; then
            echo "  -> install /etc/home-server.env (root-only)"
            ssh "$SSH_TARGET" "sudo install -m 600 -o root -g root /dev/stdin /etc/home-server.env" <<EOF
MQTT_HOST=${MQTT_HOST}
MQTT_PORT=${MQTT_PORT:-1883}
DASHBOARD_PORT=${DASHBOARD_PORT:-8080}
EOF
        fi
        unit_remote_path="$REMOTE_DIR/$SYSTEMD_UNIT"
        target_unit_path="/etc/systemd/system/$SYSTEMD_UNIT"
        echo "  -> install unit $SYSTEMD_UNIT -> $target_unit_path"
        ssh -t "$SSH_TARGET" "sudo install -m 644 -o root -g root '$unit_remote_path' '$target_unit_path' && sudo systemctl daemon-reload && sudo systemctl enable '$SYSTEMD_UNIT' && sudo systemctl restart '$SYSTEMD_UNIT'"
        return 0
    fi

    inner="$VENV_PYTHON $REMOTE_DIR/$ENTRYPOINT"

    if [ -n "$SCREEN_NAME" ]; then
        cmd="${sudo_prefix}screen -dmS $SCREEN_NAME $inner"
        echo "  -> screen: $cmd"
        # -t lets sudo prompt for a password if NOPASSWD isn't set; screen
        # detaches immediately, so the ssh call returns right away.
        ssh -t "$SSH_TARGET" "$cmd"
    else
        cmd="${sudo_prefix}$inner"
        ssh_opts=""
        # -t allocates a TTY so sudo can prompt for password on our terminal.
        [ "$RUN_AS_ROOT" = "true" ] && ssh_opts="-t"
        echo "  -> run:    $cmd"
        ssh $ssh_opts "$SSH_TARGET" "$cmd"
    fi
}

main() {
    if [ "$#" -eq 0 ]; then
        # Word-split intentional; device names are directory names we control.
        set -- $(list_all_devices)
    fi
    if [ "$#" -eq 0 ]; then
        echo "No devices found in $DEVICES_DIR" >&2
        exit 1
    fi

    ok=0; fail=0; failed_names=""
    for name in "$@"; do
        if update_device "$name"; then
            ok=$((ok + 1))
        else
            fail=$((fail + 1))
            failed_names="${failed_names}${name} "
        fi
    done

    echo
    echo "================================================================"
    echo "  Summary: $ok succeeded, $fail failed"
    if [ "$fail" -gt 0 ]; then
        echo "  Failed:  $failed_names"
    fi
    echo "================================================================"

    [ "$fail" -eq 0 ]
}

main "$@"
