/*
 * sypialnia — minimal production firmware for the bedroom CO2 node.
 *
 * Trimmed from the reference `waku` sketch. Only three responsibilities:
 *   1. OTA over Wi-Fi — the deploy transport driven by ../../../update.sh.
 *   2. Read the MH-Z19B CO2 sensor and publish it over MQTT.
 *   3. Flash the outward-facing RGB LED so the box visibly shows it is alive
 *      (TEMPORARY test indicator — see the fenced block in loop()).
 *
 * Everything else from waku (alarm, dawn light, buzzer, OLED, RTC, button,
 * LED matrix, HTTP client, FreeRTOS) is intentionally omitted. The full
 * hardware wiring table is preserved in this device's README.md for future use.
 *
 * arduino_secrets.h is generated by update.sh from the repo-root .env at
 * compile time and deleted immediately after — it is never committed.
 */
#include <WiFiS3.h>
#include <ArduinoOTA.h>
#include <ArduinoMqttClient.h>

#include "arduino_secrets.h"
#include "co2_sensor.h"

// --- Pins (from the waku wiring; see README.md) ---
static const int CO2_PWM_PIN = 2;   // PIN 2  -> MH-Z19B PWM output
static const int LED_R_PIN   = 10;  // PIN 10 -> LED #2 (red channel)
static const int LED_G_PIN   = 11;  // PIN 11 -> LED #3 (green channel)
static const int LED_B_PIN   = 9;   // PIN 9  -> LED #1 (blue channel)

// --- Timing ---
static const unsigned long CO2_PUBLISH_INTERVAL_MS = 15000;
static const unsigned long WIFI_RETRY_INTERVAL_MS  = 5000;

// --- MQTT topics (home/<device>/<metric>) ---
static const char* MQTT_TOPIC_CO2    = "home/sypialnia/co2";
static const char* MQTT_TOPIC_STATUS = "home/sypialnia/status";

WiFiClient wifiClient;
MqttClient mqttClient(wifiClient);
CO2Sensor  co2Sensor(CO2_PWM_PIN);

unsigned long lastCo2Publish = 0;

bool connectToWiFi() {
  if (WiFi.status() == WL_CONNECTED) return true;
  for (int attempt = 0; attempt < 5; attempt++) {
    Serial.print("WiFi connect attempt ");
    Serial.println(attempt + 1);
    if (WiFi.begin(SECRET_SSID, SECRET_PASS) == WL_CONNECTED) {
      Serial.print("WiFi connected, IP: ");
      Serial.println(WiFi.localIP());
      return true;
    }
    delay(WIFI_RETRY_INTERVAL_MS);
  }
  Serial.println("WiFi connection failed");
  return false;
}

void beginOta() {
  // OTA must be available whenever Wi-Fi is up; serviced by ArduinoOTA.poll()
  // in loop() every iteration (the reference waku never polled it, so its
  // OTA never actually worked).
  ArduinoOTA.begin(WiFi.localIP(), "Arduino", SECRET_OTA_PASS, InternalStorage);
}

bool connectToMqtt() {
  if (mqttClient.connected()) return true;
  if (WiFi.status() != WL_CONNECTED) return false;

  mqttClient.setId("sypialnia");
  // Last will: the broker marks us offline if the connection drops.
  mqttClient.beginWill(MQTT_TOPIC_STATUS, true, 1);
  mqttClient.print("offline");
  mqttClient.endWill();

  Serial.print("Connecting to MQTT ");
  Serial.print(MQTT_HOST);
  Serial.print(":");
  Serial.println(MQTT_PORT);
  if (!mqttClient.connect(MQTT_HOST, MQTT_PORT)) {
    Serial.print("MQTT connect failed, error ");
    Serial.println(mqttClient.connectError());
    return false;
  }
  Serial.println("MQTT connected");

  mqttClient.beginMessage(MQTT_TOPIC_STATUS, true);
  mqttClient.print("online");
  mqttClient.endMessage();
  return true;
}

void publishCo2() {
  int ppm = co2Sensor.readPWM();
  bool valid = ppm > 0;
  String payload = String("{\"ppm\":") + ppm +
                   ",\"valid\":" + (valid ? "true" : "false") + "}";
  mqttClient.beginMessage(MQTT_TOPIC_CO2, true);
  mqttClient.print(payload);
  mqttClient.endMessage();
  Serial.print("Published ");
  Serial.print(MQTT_TOPIC_CO2);
  Serial.print(" -> ");
  Serial.println(payload);
}

void setup() {
  Serial.begin(9600);
  unsigned long t0 = millis();
  while (!Serial && millis() - t0 < 3000) { ; }  // don't block forever headless
  Serial.println("\nsypialnia waking up...");

  pinMode(LED_R_PIN, OUTPUT);
  pinMode(LED_G_PIN, OUTPUT);
  pinMode(LED_B_PIN, OUTPUT);

  co2Sensor.begin();

  connectToWiFi();
  beginOta();
  connectToMqtt();
}

void loop() {
  // 1. OTA — poll every iteration so a deploy is never missed.
  ArduinoOTA.poll();

  // 2. Keep the network up; re-arm OTA after a reconnect.
  if (WiFi.status() != WL_CONNECTED) {
    if (connectToWiFi()) beginOta();
  }
  if (!mqttClient.connected()) {
    connectToMqtt();
  } else {
    mqttClient.poll();
  }

  // 3. Publish CO2 on a fixed cadence.
  unsigned long now = millis();
  if (now - lastCo2Publish >= CO2_PUBLISH_INTERVAL_MS) {
    lastCo2Publish = now;
    if (mqttClient.connected()) publishCo2();
  }

  // ===== TEMPORARY heartbeat (test only — remove before production) =========
  // Colorful rotating glow on the outward-facing RGB LED so the box visibly
  // shows the firmware is alive. To retire the indicator, delete this whole
  // fenced block plus the LED_*_PIN consts and their pinMode() calls.
  {
    float phase = (now % 3000) / 3000.0f * 2.0f * PI;
    int r = (int)(127.0f + 127.0f * sin(phase));
    int g = (int)(127.0f + 127.0f * sin(phase + 2.094f));   // +120 deg
    int b = (int)(127.0f + 127.0f * sin(phase + 4.189f));   // +240 deg
    analogWrite(LED_R_PIN, r);
    analogWrite(LED_G_PIN, g);
    analogWrite(LED_B_PIN, b);
  }
  // ===== end TEMPORARY heartbeat ===========================================
}
